version: '3.4'

services:
    Shorten-URL:
        image: klt2601/shorten-url
        ports:
            - '5000:5000'
        expose:
            - '5000'
        restart: always
volumes:
    db-config:
    db-data:
